import JSZip from 'jszip';
import personalBrandRaw from '../components/templates/TemplatePersonalBrand.jsx?raw';
import amanDevRaw from '../components/templates/TemplateAmanDev.jsx?raw';
import modernDarkRaw from '../components/templates/TemplateModernDark.jsx?raw';
import creativeRaw from '../components/templates/TemplateCreative.jsx?raw';
import minimalRaw from '../components/templates/TemplateMinimal.jsx?raw';
import classicRaw from '../components/templates/TemplateClassic.jsx?raw';
import socialIconsRaw from '../components/SocialIcons.jsx?raw';
import imageCarouselRaw from '../components/ImageCarousel.jsx?raw';
import indexCssRaw from '../index.css?raw';

const templateRawMap = {
  'personal-brand': { code: personalBrandRaw, componentName: 'TemplatePersonalBrand' },
  'aman-dev': { code: amanDevRaw, componentName: 'TemplateAmanDev' },
  'modern-dark': { code: modernDarkRaw, componentName: 'TemplateModernDark' },
  'creative': { code: creativeRaw, componentName: 'TemplateCreative' },
  'minimal': { code: minimalRaw, componentName: 'TemplateMinimal' },
  'classic': { code: classicRaw, componentName: 'TemplateClassic' }
};

export const exportPortfolioAsZip = async (portfolioData) => {
  const zip = new JSZip();

  const selectedKey = portfolioData.templateKey || 'personal-brand';
  const templateInfo = templateRawMap[selectedKey] || templateRawMap['personal-brand'];
  const nameSlug = portfolioData.name 
    ? portfolioData.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
    : 'portfolio';

  // 1. package.json
  const packageJson = {
    name: `${nameSlug}-portfolio`,
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: {
      "dev": "vite",
      "build": "vite build",
      "preview": "vite preview"
    },
    dependencies: {
      "lucide-react": "^1.45.0",
      "react": "^19.2.8",
      "react-dom": "^19.2.8"
    },
    devDependencies: {
      "@vitejs/plugin-react": "^6.1.1",
      "vite": "^8.3.0"
    }
  };

  zip.file("package.json", JSON.stringify(packageJson, null, 2));

  // 2. vite.config.js
  const viteConfig = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;
  zip.file("vite.config.js", viteConfig);

  // 3. index.html
  const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${portfolioData.name || 'Portfolio'} - Personal Website</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;
  zip.file("index.html", indexHtml);

  // 4. README.md
  const readmeMd = `# ${portfolioData.name || 'Personal'} Portfolio Code

This is your complete standalone React + Vite portfolio codebase generated by Portfolio Generator.

## 🚀 How to Run Locally

1. **Open terminal** in this project folder:
   \`\`\`bash
   cd ${nameSlug}-portfolio
   \`\`\`

2. **Install dependencies**:
   \`\`\`bash
   npm install
   \`\`\`

3. **Start local development server**:
   \`\`\`bash
   npm run dev
   \`\`\`

4. Open \`http://localhost:5173\` in your browser to view your live portfolio!

## 📦 How to Deploy

- **Vercel / Netlify**: Push this folder to GitHub and import into Vercel/Netlify.
- **GitHub Pages**: Run \`npm run build\` and deploy the generated \`dist\` folder.
`;
  zip.file("README.md", readmeMd);

  // 5. src/portfolioData.json
  zip.file("src/portfolioData.json", JSON.stringify(portfolioData, null, 2));

  // 6. src/index.css
  zip.file("src/index.css", indexCssRaw || `body { margin: 0; font-family: system-ui, sans-serif; }`);

  // 7. src/main.jsx
  const mainJsx = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
  zip.file("src/main.jsx", mainJsx);

  // 8. src/App.jsx
  const appJsx = `import React from 'react';
import ${templateInfo.componentName} from './components/templates/${templateInfo.componentName}.jsx';
import portfolioData from './portfolioData.json';

export default function App() {
  return <${templateInfo.componentName} portfolioData={portfolioData} />;
}
`;
  zip.file("src/App.jsx", appJsx);

  // 9. src/components/SocialIcons.jsx
  zip.file("src/components/SocialIcons.jsx", socialIconsRaw);

  // 10. src/components/ImageCarousel.jsx
  zip.file("src/components/ImageCarousel.jsx", imageCarouselRaw);

  // 11. src/components/templates/[SelectedTemplate].jsx
  zip.file(`src/components/templates/${templateInfo.componentName}.jsx`, templateInfo.code);

  // Generate ZIP blob and trigger browser download
  const content = await zip.generateAsync({ type: "blob" });
  const downloadUrl = URL.createObjectURL(content);
  const anchor = document.createElement("a");
  anchor.href = downloadUrl;
  anchor.download = `${nameSlug}-portfolio-react-code.zip`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(downloadUrl);
};
